# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
    kubernetesVersion: v1.14.10

nodes:
- role: control-plane
- role: worker
- role: worker
