apiVersion: batch/v1
kind: Job
metadata:
  name: s3cp-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      name: s3cp-job
    spec:
      restartPolicy: Never
      containers:
        - name: pgdump-job 126197467950
          image: "123456789123.dkr.ecr.ap-northeast-1.amazonaws.com/hoge/fuga:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "ap-northeast-1"
            - name: AWS_BUCKET_NAME
              value: "kondoh"
            - name: AWS_BUCKET_BACKUP_PATH
              value: "backup"
