name: "Create cluster using KinD"
on:
 push:
  paths:
  - k8s/**
  - .github/workflows/it_k8s.yml

jobs:
  kind:
    # strategy:
    #   matrix:
    #     k8s: [1.15.7]
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Kubernetes cluster with kind
      run : kind create cluster --wait 5m
    - name: Testing
      run: |
        cat ~/.kube/config
        kubectl version
        kubectl cluster-info
        kubectl get node -o wide
        kubectl get pods -n kube-system
        kubectl apply -f k8s/nginx_deploy.yml
        kubectl describe deployment nginx-deployment
