name: Multi Stage Build
on:
  push:
    paths:
    - .github/workflows/multi_stage_job.yml

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Build
      run: echo Build

  TestA:
    runs-on: ubuntu-latest
    needs: Build
    name: Run Test A
    steps:
    - name: Test A
      run: echo Test A

  TestB:
    runs-on: ubuntu-latest
    needs: Build
    name: Run Test B
    steps:
    - name: Test B
      run: echo Test B

  Deploy:
    runs-on: ubuntu-latest
    needs: [TestA, TestB]
    steps:
    - name: Deploy
      run: echo Deploy

  Notify:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
    - name: Notify to Slack channel
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: kondoumh
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
