name: Multi Stage Build
on:
  push:
    paths:
    - .github/workflows/multi_stage_job.yml

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build
    outputs:
      done: ${{ steps.check.outputs.message }}
    steps:
    - name: Build
      run: echo Build
    - id: check
      run: echo "::set-output name=message::Build"

  TestA:
    runs-on: ubuntu-latest
    needs: Build
    outputs:
      done: ${{ steps.check.outputs.message }}
    name: Run Test A
    steps:
    - name: Test A
      run: echo Test A
    - id: check
      run: echo "::set-output name=message::Test A"

  TestB:
    runs-on: ubuntu-latest
    needs: Build
    outputs:
      done: ${{ steps.check.outputs.message }}
    name: Run Test B
    steps:
    - name: Test B
      run: |
        echo Test B
    - id: check
      run: echo "::set-output name=message::Test B"

  Deploy:
    runs-on: ubuntu-latest
    needs: [TestA, TestB]
    outputs:
      done: ${{ steps.check.outputs.message }}
    steps:
    - name: Deploy
      run: echo Deploy
    - id: check
      run: echo "::set-output name=message::Deploy"

  Notify_succeed:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: [Build, TestA, TestB, Deploy]
    steps:
    - name: Notify to Slack channel
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHUb Actions
        SLACK_TITLE: 'Workflow #${{ github.run_number }} succeeded'
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        SLACK_MESSAGE: '${{ needs.Build.outputs.done }} ${{ needs.TestA.outputs.done }} ${{ needs.TestB.outputs.done }} ${{ needs.Deploy.outputs.done }}'

  Notify_failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [Build, TestA, TestB, Deploy]
    steps:
    - name: Notify to Slack channel
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHUb Actions
        SLACK_TITLE: 'Workflow #${{ github.run_number }} failed'
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        SLACK_COLOR: danger
        SLACK_MESSAGE: '${{ needs.Build.outputs.done }} ${{ needs.TestA.outputs.done }} ${{ needs.TestB.outputs.done }} ${{ needs.Deploy.outputs.done }}'
