name: "Use internal action"
on:
 push:
  paths:
  - .github/workflows/use-internal-action.yml

jobs:
  call-intenral-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        reppsitory: kondoumh/setup-helmfile
        token: ${{ secrets.GITHUB_TF_TOKEN }}
        path: actions
    - name: Test
      run: |
        ls -l actions
